#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$HBCI_DATABASE_NAME" <<-EOSQL
	CREATE USER $APP_USERNAME WITH PASSWORD '$APP_PASSWORD';
	CREATE DATABASE $APP_USERNAME;
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $APP_USERNAME;
	ALTER DATABASE $APP_USERNAME OWNER TO $APP_USERNAME;
	CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
	CREATE EXTENSION IF NOT EXISTS "postgis";
EOSQL


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$APP_USERNAME" <<-EOSQL
    DROP EXTENSION IF EXISTS "uuid-ossp" ;
    DROP EXTENSION IF EXISTS "postgis" ;
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "postgis";
EOSQL


