#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$HBC_DATABASE_NAME" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
	CREATE USER $APP_USERNAME WITH PASSWORD '$APP_PASSWORD';
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $APP_USERNAME;
	ALTER DATABASE $HBC_DATABASE_NAME OWNER TO $APP_USERNAME;
EOSQL

