<?php

namespace App\Api\Actions\AInterfaces;

use App\Models\ThingResult;

/**
 * todo each action only has one class that defines the output, and it has open api attributes, and renders the json
 *   So, in summary, each action has the following required classes:
 *      * parameters interface (see if interface can define the open api) that has setters for the needed data, and does validation of the input data
 *      * parameters class (put open api attributes here if cannot do the interface for that)
 *      * A logic class which is called by the thing row when it processes, the thing stores the params in json and rehydrates the params
 *      * A response interface that defines the data output with getters for the produced data (again open api or use class below)
 *      * A response class that generates the json or other format output, this is given back to the thing to store as a response
 *
 *
 * todo delete all the interfaces in this folder, except a generic  ActionParams, ActionLogic, ActionResponse
 *  and a simple action work return that has the thing response .
 *   The thing will give the correct interface for filling in the params, and calling its work, using its class map generated by the hbc:system build
 *
 * todo this gets data from the @see ThingResult, Thing root
 * and will process it to json,and set the result with its generated stuff, its given the thing root, holding the data, via the result for a reference
 */
interface IActionOutput
{

    public function setThingOutput(ThingResult $result) : array ;
}
