<?php

namespace App\Api\Ta;

use App\Models\Thing;

/**
 * gather data in setters
 * connect to thing to write setup data at the root
 * put actions in the tree, under root, do multiple layers (search->action->root)
 * things needs some methods here (create_root,create_node,add_child,push_node)
 * for the setup, create the thing structure, and at each node tell thing to use the IActionParams (that it gets from the thing map) for the action to use
 * The open api type for the required data is defined in a params class in the folder, or in the class that implements this
 *
 * todo workflow :
 *  When wanting to start an api, get that api setup from the api map generated by the console, and make a new object,it will have setters, fill in the setters
 *   some setters may just be a collection, that is ok
 *  Then call push data and setupActions on here, the push will add the processed data to the thing api-setup data, the setup actions will setup the tree
 *  Eventually the thing will be run tree leafs first
 *  When its run, the thing will look at the action in that row, and find the correct params class, make a new one and call the pull data for it
 *   The params will know where in the thing it gets the data from
 *   Then the thing will find the correct worker class, and pass in the params object
 *   The worker class will return the actionReturn,
 *     if the return shows it has an error, then the thing tree will finish, and the root will write the error
 *      otherwise the thing will call on that to write the data to the same thing it got the param data, and mark it current:
 *   Keep working up the thing tree until the parent is reached
 *   Once the parent is reached, then we do the ApiOutput, but getting the class from the map, making an object, and call write return
 *    the write return can only fill in and use classes that are marked as ApiOutput per the OA return defined on this class
 *
 */
interface IApiSetup
{
    public function pushData(Thing $thing): void ;
    public function setupActions(Thing $thing): void ;
}
