<?php

namespace App\Api\ThingApi;


use App\Models\Thing;

/**
 * gather data in setters
 * connect to thing to write setup data at the root
 * put actions in the tree, under root, do multiple layers (search->action->root)
 * things needs some methods here (create_root,create_node,add_child,push_node)
 * for the setup, create the thing structure, and at each node tell thing to use the IActionParams (that it gets from the thing map) for the action to use
 * The open api type for the required data is defined in a params class in the folder, or in the class that implements this
 *
 * todo workflow for thing api:
 *  When wanting to start an api, get that api IApiThingSetup and IApiOaParams from the api map generated by the console, This may be the same or different classes
 *  and make a new params object, fill it from the request. Then make the thing setup if different class, and call the push to thing and setup actions
 *    The params object will have the OA input stuff
 *  When the thing root returns, after all the actions are done, then it will find in the map the IApiThingResult to write the data to the thing result
 *  The IApiOaResponse may be the same class. The IApiThingResult will have its static method called using the object of the IApiOaResponse
 *   The actions can list the actions they use, this is a method on the IApiThingSetup. Any actions listed here will be made into children of the api root thing
 *
 *  todo for actions
 *   actions can be called from an api call, or called because they are a rule
 *   during either call, the action will find its initial data in the runtime data on its current node.
 *   the things will transfer the data from the event or api to the leaf setup data the action is in, or else, the child things will set the action node
 *   when the action is invoked, it has a static work method, and that receives the params class that knows how to read the data in the curren thing
 *      this is IActionWork and IActionParams, and they can be the same class or different.
 *    The things will get the correct class for each from the mapping: the params will be instantiated, then sent as a param to the static method,
 *    the work method will return IActionWorkResult which can write to the thing, this can also be a different or the same class

 *
 * todo for the thing data flow
 *  Thing trees will be run leafs first,
 *      leaves from trees that are from the api calls will be given the api data
 *      leaves from trees that are from events will be given the event data
 *      Both have the new data placed in the leaf thing set as the run time data
 *  When its run, the thing will look at the action in that row, and find the correct params class, make a new one and call the pull data for it
 *   if any action or api class run by the thing throws an exception, then the api tree, or event tree will be terminated
 *    The root of that tree will record the exception info. If api root that is all the api call. If event root then the other events still proceed.
 *
 *
 */
interface IApiThingSetup
{
    public function pushData(Thing $thing): void ;

    /**
     * @return array
     */
    public function getActions(): array ;
}
